# Generated by Django 4.1.7 on 2023-03-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('m_name', models.CharField(blank=True, max_length=30, verbose_name='Middle Name')),
                ('l_name', models.CharField(max_length=30, verbose_name='Last Name')),
            ],
        ),
    ]
