# Generated by Django 4.1.7 on 2023-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='other',
            field=models.BooleanField(default=False, verbose_name='Prefer not to say'),
        ),
    ]
